### PR TITLE
CARRY: Update go build to v1.21

### PR DESCRIPTION
**Pull request by VanillaSpoon**
Issue Link: [here](https://issues.redhat.com/browse/RHOAIENG-6400)

There are currently no UBI 8 images available that support Go 1.21, which will be required to merge: https://github.com/project-codeflare/codeflare-operator/pull/541

A similar issue was previously addressed in cpass where a workaround was implemented

### CODE REVIEW

**Comment by astefanutti** [comment]
/hold

Just holding it until 2.9 is officially release so it does not end up in it by accident.

**Comment by astefanutti** [comment]
Otherwise LGTM :)

**Comment by astefanutti** [comment]
@VanillaSpoon is it good to go now?

**Comment by KPostOffice** [comment]
I think this needs some changes after [@dgrove-oss changes](https://github.com/project-codeflare/codeflare-operator/pull/541/files). It should be enough to just change the GOLANG_IMAGE to be an approved image

**Comment by ChristianZaccaria** [comment]
Closing as done: https://github.com/red-hat-data-services/codeflare-operator/pull/22

**Pull request closed without merging**
